services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    expose:
      - "5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 2
    networks:
      - omniscient
  
  postgres_db:
    image: postgres:latest
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    networks:
      - omniscient
  
  cleaner-service:
    image: omniscient-cleaner-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dotnet-aspire:18889
      - OTEL_RESOURCE_ATTRIBUTES=service.name=Omniscient.Cleaner
      - SERVICE_INSTANCE_ID={{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}
      - WAIT_HOSTS=rabbitmq:5672,postgres_db:5432
    networks:
      - omniscient
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./.enron-files:/app/.enron-files
    command: ["dotnet", "Omniscient.Cleaner.dll", "--init", "--path=/app/.enron-files/maildir" ]
  
  indexer-service:
    image: omniscient-indexer-service
    expose:
      - "8081"
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_CONNECTION_STRING=HOST=postgres_db;PORT=5432;DB=Omniscient;UID=root;PWD=password;
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dotnet-aspire:18889
      - OTEL_SERVICE_NAME=Omniscient.Indexer
      - SERVICE_INSTANCE_ID={{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}
      - WAIT_HOSTS=rabbitmq:5672,postgres_db:5432
    networks:
      - omniscient
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated 
      replicas: 1 # TODO: Increase replicas to 3
  
  blazor-ui:
    image: omniscient-blazor-ui
    depends_on:
      - indexer-service
    ports:
      - "8080:8080"
    networks:
      - omniscient
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dotnet-aspire:18889
      - OTEL_SERVICE_NAME=Omniscient.Web
      - INDEXER_BASE_ADDRESS=http://indexer-service:8081/
      - SERVICE_INSTANCE_ID={{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}
  
  dotnet-aspire:
    image:  mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "18888:18888"
    expose:
      - "18889"
    networks:
      - omniscient
      
volumes:
  omniscient:

networks:
  omniscient: