services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 2
    networks:
      - omniscient
  
  postgres_db_shard1:
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    networks:
      - omniscient

  postgres_db_shard2:
    image: postgres:latest
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    networks:
      - omniscient
  
  cleaner-service:
    build:
      context: .
      dockerfile: Omniscient.Cleaner/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dotnet-aspire:18889
      - OTEL_RESOURCE_ATTRIBUTES=service.name=Omniscient.Cleaner
      - WAIT_HOSTS=rabbitmq:5672
    volumes:
      - ./.enron-files:/app/.enron-files
    command: ["dotnet", "Omniscient.Cleaner.dll", "--init", "--path=/app/.enron-files/maildir" ]    
    networks:
      - omniscient
  
  indexer-service-shard1:
    build:
      context: .
      dockerfile: Omniscient.Indexer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres_db_shard1:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_CONNECTION_STRING=HOST=postgres_db_shard1;PORT=5432;DB=Omniscient;UID=root;PWD=password;
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dotnet-aspire:18889
      - OTEL_SERVICE_NAME=Omniscient.Indexer
      - SENDER_START=A
      - SENDER_END=M
      - WAIT_HOSTS=rabbitmq:5672,postgres_db_shard1:5432
    networks:
      - omniscient

  indexer-service-shard2:
    build:
      context: .
      dockerfile: Omniscient.Indexer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres_db_shard2:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8081"
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_CONNECTION_STRING=HOST=postgres_db_shard2;PORT=5432;DB=Omniscient;UID=root;PWD=password;
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dotnet-aspire:18889
      - OTEL_SERVICE_NAME=Omniscient.Indexer
      - SENDER_START=N
      - SENDER_END=Z
      - WAIT_HOSTS=rabbitmq:5672,postgres_db_shard2:5432
    networks:
      - omniscient
  
  blazor-ui:
    build:
      context: .
      dockerfile: Omniscient.Web/Dockerfile
    depends_on:
      - indexer-service-shard1
      - indexer-service-shard2
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dotnet-aspire:18889
      - OTEL_SERVICE_NAME=Omniscient.Web
      - INDEXER_BASE_ADDRESS=http://indexer-service-shard1:8081/
    networks:
      - omniscient
        
  dotnet-aspire:
   image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
   ports:
     - "18888:18888"
     - "18889:18889"
   networks:
     - omniscient

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    networks:
      - omniscient
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - omniscient
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana-provisioning/dashboards:/var/lib/grafana/dashboards
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped
    
networks:
  omniscient: