receivers:
  otlp:
    protocols:
      grpc:
      http:

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['localhost:8889']

processors:
  batch:

exporters:
  otlp:
    endpoint: "jaeger:14250"  # Send traces to Jaeger via OTLP
    tls:
      insecure: true

  prometheus:
    endpoint: "otel-collector:8889"  # Prometheus scrape endpoint

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    metrics:
      receivers: [prometheus]  # Collect metrics from Prometheus
      exporters: [prometheus]  # Export collected metrics to Prometheus

