{
 "title": "Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (increase(http_server_request_duration_seconds_count{otel_scope_name=\"Microsoft.AspNetCore.Hosting\", http_response_status_code=~\"4..|5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (increase(http_server_request_duration_seconds_count{otel_scope_name=\"Microsoft.AspNetCore.Hosting\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Searching Performance",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(search_performance_milliseconds_bucket[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexing Performance",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(indexing_duration_milliseconds_bucket[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_request_duration_seconds_sum[1m])) / avg(rate(http_server_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{otel_scope_name=\"Microsoft.AspNetCore.Hosting\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}